---
title: "SDA_homework1"
author: "Christine Katabarwa"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Importing data
```{r}
data<-read.csv("C:\\Users\\chris\\OneDrive\\Documents\\BIOSTAT 2\\SEM 1\\sda\\Homework\\HW1\\hodgkin2b.csv")
library(survival)
library(survminer)
library(ggplot2)
library(dplyr)
```

## Survival function for the event
```{r}
event_fit <- survfit(Surv(firsttime, event) ~ 1, data = data)
plot(event_fit, xlab = "Time(months)", ylab = "Survival Probability", col = c("red"),lty = 1)

```

## age
```{r}
data$age_group <- cut(data$age, breaks=c(0, 40, 60, 100), labels=c("Young", "Middle", "Old"))
age_ranges <- tapply(data$age, data$age_group, range)
age_ranges

age_fit <- survfit(Surv(firsttime, event) ~ age_group, data = data)
#plot(age_fit, xlab = "Time(months)", ylab = "Survival Probability", col = c("red"),lty = 1)
# Plot the survival curves for each age group
plot(age_fit, 
     xlab = "Survival Time (Days)", 
     ylab = "Survival Probability", 
     main = "Survival Curves by Age Group", 
     col = c("blue", "orange", "green"), # Colors for age groups
     lty = 1)
legend("topright", 
       legend = levels(data$age_group),  # Age group labels
       col = c("blue", "orange", "green"), 
       lty = 1)


```


## effect of sex
```{r}
sex_fit <- survfit(Surv(firsttime, event) ~ male , data = data)

plot(sex_fit, 
     xlab = "Survival Time (Months)", 
     ylab = "Survival Probability", 
     main = "Survival Curves by sex", 
     col = c("red", "green"), 
     lty = 1)
legend("topright", 
       legend = c("Male", "Female"), 
       col = c("red", "green"), 
       lty = 1)


```

## Clinical stage effect on survival time
```{r}
clinstg_fit <- survfit(Surv(firsttime, event) ~ clinstg , data = data)

plot(clinstg_fit, 
     xlab = "Survival Time (Months)", 
     ylab = "Survival Probability", 
     main = "Survival Curves by clinical stage", 
     col = c("blue", "red"), 
     lty = 1)
legend("topright", 
       legend = c("1", "2"), 
       col = c("blue", "red"), 
       lty = 1)

```

## Presence of extra nodal disease
```{r}
nodes_fit <- survfit(Surv(firsttime, event) ~ nodes , data = data)

plot(nodes_fit, 
     xlab = "Survival Time (Months)", 
     ylab = "Survival Probability", 
     main = "Survival Curves by nodal disease", 
     col = c("blue", "red"), 
     lty = 1)
legend("topright", 
       legend = c("1", "0"), 
       col = c("blue", "red"), 
       lty = 1)


```

## mediastinum involvement
```{r}
mediast_fit <- survfit(Surv(firsttime, event) ~ mediast , data = data)

plot(mediast_fit, 
     xlab = "Survival Time (Months)", 
     ylab = "Survival Probability", 
     main = "Survival Curves by mediastinum involvement", 
     col = c("blue", "red","green"), 
     lty = 1)
legend("topright", 
       legend = c("large","small","none"),
       col = c("blue", "red","green"), 
       lty = 1)

## or
ggsurvplot(mediast_fit, data = data,
           #fun = "pct",
           risk.table = TRUE, 
           #tables.theme = theme_cleantable(),
           fontsize = 3.5,
           risk.table.height=0.3,
           pval = TRUE,
           #conf.int = TRUE,
           surv.median.line = "hv",
           legend.title = "mediast")


```

## addition of chemotherapy to radiotherapy
```{r}
cmt_fit <- survfit(Surv(firsttime, event) ~ cmt , data = data)

plot(cmt_fit, 
     xlab = "Survival Time (Months)", 
     ylab = "Survival Probability", 
     main = "Survival Curves by cmt", 
     col = c("blue", "red"), 
     lty = 1)
legend("topright", 
       legend = c("1","0"), 
       col = c("blue", "red"), 
       lty = 1)
```


```{r}

cmt_fit <- survfit(Surv(firsttime, event) ~ cmt , data = data)


# Plot survival curves
ggsurvplot(cmt_fit, data = data,
           #fun = "pct",
           risk.table = TRUE, 
           #tables.theme = theme_cleantable(),
           fontsize = 3.5,
           risk.table.height=0.3,
           pval = TRUE,
           conf.int = TRUE,
           surv.median.line = "hv",
           legend.title = "cmt")




```

```{r}
data$age_group <- cut(data$age, 
                      breaks = c(0, 40, 60, 100), 
                      labels = c("Young", "Middle", "Old"), 
                      right = FALSE,
                      ordered_result = TRUE)  # Ordered factor

# Performing the log-rank test for trend
logrank_test_trend <- survdiff(Surv(firsttime, event) ~ age_group, data = data)
print(logrank_test_trend)

#Ho: The survival functions are the same
#Ha: the functions are different

# From the output, we reject Ho and conclude that the survival functions are not the same.
```

## Logrank test for sex
```{r}
logrank_sex <- survdiff(Surv(firsttime, event) ~ male, data = data)
print(logrank_sex)


#Ho: The survival functions are the same
#Ha: the functions are different

# From the output, we fail to reject Ho and conclude that the survival functions are the same.

```
## nodes
```{r}
logrank_nodes <- survdiff(Surv(firsttime, event) ~ nodes, data = data)
print(logrank_nodes)


#Ho: The survival functions are the same
#Ha: the functions are different

# From the output, we fail to reject Ho and conclude that the survival functions are the same.

```


## cmt
```{r}
logrank_cmt <- survdiff(Surv(firsttime, event) ~ cmt, data = data)
print(logrank_cmt)


#Ho: The survival functions are the same
#Ha: the functions are different

# From the output, we reject Ho and conclude that the survival functions are not the same.

```


## mediast
```{r}
logrank_mediast <- survdiff(Surv(firsttime, event) ~ mediast, data = data)
print(logrank_mediast)


#Ho: The survival functions are the same
#Ha: the functions are different

# From the output, we reject Ho and conclude that the survival functions are not the same.

```


## stratified logrank
```{r}
data<-data %>%
      mutate(age_new=ifelse(data$age<40,"<40",
                              ifelse(data$age>65,"+65","40-65")))

logrank_strata<- survdiff(Surv(firsttime, event) ~ cmt + strata(age_new,male,mediast,nodes,clinstg), data = data)
print(logrank_strata)

logrank_strata1<- survdiff(Surv(firsttime, event) ~ cmt + strata(age_new), data = data)
print(logrank_strata1)

logrank_strata2<- survdiff(Surv(firsttime, event) ~ cmt + strata(male), data = data)
print(logrank_strata2)

logrank_strata3<- survdiff(Surv(firsttime, event) ~ cmt + strata(mediast), data = data)
print(logrank_strata3)

logrank_strata4<- survdiff(Surv(firsttime, event) ~ cmt + strata(nodes), data = data)
print(logrank_strata4)

logrank_strata5<- survdiff(Surv(firsttime, event) ~ cmt + strata(clinstg), data = data)
print(logrank_strata5)


#Ho: The survival functions are the same
#Ha: the functions are different

# From the output, we reject Ho and conclude that the survival functions are not the same.

```
